# Generated by Django 5.1.6 on 2025-02-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerprofile',
            name='license_number',
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='about',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=50, unique=True),
        ),
    ]
