# Generated by Django 5.1.6 on 2025-03-01 09:33

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_engineerprofile_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to=common.models.license_upload_path),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='license_number',
            field=models.CharField(default='DEFAULT123', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=common.models.profile_image_upload_path),
        ),
    ]
