# Generated by Django 5.1.6 on 2025-03-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_engineerprofile_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerprofile',
            name='license_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
