# Generated by Django 5.1.6 on 2025-03-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_engineerprofile_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerprofile',
            name='address',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
