# Generated by Django 5.1.6 on 2025-03-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_engineerprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerprofile',
            name='address',
            field=models.CharField(default='default address', max_length=50),
        ),
    ]
