# Generated by Django 5.1.6 on 2025-03-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_engineerprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkprofile',
            name='about',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clerkprofile',
            name='position',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
