# Generated by Django 5.1.6 on 2025-03-05 16:11

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_clerkprofile_about_clerkprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=common.models.clerk_profile_image_upload_path),
        ),
    ]
