# Generated by Django 5.1.6 on 2025-03-06 04:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_clerkprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='common.clerkprofile')),
            ],
        ),
    ]
