# Generated by Django 5.1.6 on 2025-03-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
