# Generated by Django 5.1.6 on 2025-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerkprofile',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
