# Generated by Django 5.1.6 on 2025-03-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_clerkprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='addrress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
