# Generated by Django 5.1.6 on 2025-03-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_profile_addrress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='addrress',
            new_name='adrress',
        ),
    ]
