# Generated by Django 5.1.6 on 2025-03-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_rename_addrress_profile_adrress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adrress',
            new_name='address',
        ),
    ]
