# Generated by Django 5.1.6 on 2025-03-13 15:44

import django.db.models.deletion
import engineer.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_userdocument_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_document', models.FileField(upload_to=engineer.models.engineer_document_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('clerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_clerk', to=settings.AUTH_USER_MODEL)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_documents', to=settings.AUTH_USER_MODEL)),
                ('user_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_docs', to='user.userdocument')),
            ],
        ),
    ]
