# Generated by Django 5.1.6 on 2025-03-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0003_attendance_delete_clerkattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='employee_name',
        ),
    ]
