# Generated by Django 5.1.6 on 2025-03-13 15:44

import clerk.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0004_remove_attendance_employee_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClerkDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_document', models.FileField(upload_to=clerk.models.clerk_document_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clerk_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
