# Generated by Django 5.1.6 on 2025-03-11 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0004_remove_attendance_employee_name'),
        ('common', '0014_alter_clerkprofile_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.clerkprofile')),
            ],
        ),
    ]
