# Generated by Django 5.1.6 on 2025-03-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0005_clerkdocument'),
        ('engineer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkdocument',
            name='engineer_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clerk_docs', to='engineer.engineerdocument'),
        ),
    ]
