# Generated by Django 5.1.6 on 2025-03-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0005_leaverequest'),
        ('clerk', '0008_clerkdocument_status'),
    ]

    operations = [
    ]
