# Generated by Django 5.1.6 on 2025-03-17 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0009_merge_0005_leaverequest_0008_clerkdocument_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clerk_calls', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_calls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
