# Generated by Django 5.1.6 on 2025-04-13 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0010_videocall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminToClerkSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_clerk_suggestions', to=settings.AUTH_USER_MODEL)),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_admin_suggestions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_suggestions', to='clerk.clerkdocument')),
            ],
        ),
    ]
