# Generated by Django 5.1.6 on 2025-03-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdocument_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
