# Generated by Django 5.1.6 on 2025-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userdocument_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('Property', 'Property Tax'), ('Water', 'Water Tax'), ('Professional', 'Professional Tax'), ('Other', 'Other')], max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('ward', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Net Banking', 'Net Banking'), ('Cash', 'Cash')], max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
