# Generated by Django 5.1.6 on 2025-04-12 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_taxpayment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Road', 'Road Issues'), ('Drainage', 'Drainage Problems'), ('Water', 'Water Supply Issues'), ('Electricity', 'Electricity Complaints'), ('Waste', 'Waste Management'), ('Other', 'Other')], max_length=50)),
                ('ward', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
