# Generated by Django 5.1.6 on 2025-04-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='phone',
        ),
    ]
