# Generated by Django 5.1.6 on 2025-03-13 15:44

import django.db.models.deletion
import panchayath_ad.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clerk', '0005_clerkdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_document', models.FileField(upload_to=panchayath_ad.models.admin_document_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_documents', to=settings.AUTH_USER_MODEL)),
                ('clerk_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_docs', to='clerk.clerkdocument')),
            ],
        ),
    ]
