# Generated by Django 5.1.6 on 2025-03-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayath_ad', '0002_admindocument_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindocument',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
